name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby_version }} / ActionView ${{ matrix.actionview_version }}
    strategy:
      matrix:
        ruby_version: [ruby-head, '3.3', '3.2', '3.1']
        actionview_version: ['7.1', '7.0', '6.1']

    env:
      ACTIONVIEW_VERSION: ${{ matrix.actionview_version }}
      COVERAGE: true

    steps:
    - uses: actions/checkout@v4

    - run: rm -f Gemfile.lock

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: true
      continue-on-error: ${{ matrix.ruby_version == 'ruby-head' }}

    - run: bundle exec rake
      continue-on-error:  ${{ matrix.ruby_version == 'ruby-head' }}

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: svyatov/clsx-rails
      # Only upload coverage for the latest Ruby and ActionView versions
      if: ${{ matrix.ruby_version == '3.3' && matrix.actionview_version == '7.1' }
